server:
  port: 8086


jwt:
  secret: 'linkgoo'
  #过期时间
  expiration: 6000000
  header: 'authorization'



spring:
  #不要为我们工程中的资源文件建立映射
  resources:
    add-mappings: false
  mvc:
    #404 抛出异常，方便统一处理
    throw-exception-if-no-handler-found: true
  #默认使用JDK代理 ，如果使用CGLib 请改为true
  servlet:
    multipart:
  # 最大支持文件大小
      max-file-size: 1000MB
  # 最大支持请求大小
      max-request-size: 1000MB
  aop:
    proxy-target-class: false
  datasource:
    url: jdbc:mysql://localhost:3306/woundstoma?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&&allowPublicKeyRetrieval=true
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: 123123
    hikari:
      minimum-idle: 3
      maximum-pool-size: 10
      max-lifetime: 30000   #不能小于30秒，否则默认回到1800秒
      connection-test-query: SELECT 1




#mybatis
#mybatis映射下划线转驼峰开启
mybatis:
  configuration:
    map-underscore-to-camel-case: true
##  interceptors:
#  #配置实体类包路径
  type-aliases-package: com.linkgoo.framework.web.entity
#  #配置mapper文件地址
  mapper-locations: classpath:mapper/**/*.xml

#开启debug
logging:
  level:
    com.linkgoo.framework.web.repository.**.*: debug

